apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 10
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.commitstoEnvironment }}"
        - name: ENV_NAME
          value: "{{ .Values.commitstoEnvName }}"
        - name: PAPERTRAIL_HOST
          value: "{{ .Values.commitstoPapertrailHost }}"
        - name: PAPERTRAIL_PORT
          value: "{{ .Values.commitstoPapertrailPort }}"
        - name: APP_DOMAIN
          value: "{{ .Values.commitstoAppDomain }}"
        - name: DATABASE_URL
          value: "postgres://{{ .Values.externalDatabase.user }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}"
        - name: PORT
          value: "{{ .Values.service.internalPort }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
